### ISSUE TITLE
semicolon in annotation(Documentation(info breaks syntax highlight

### ISSUE THREAD

**Issue by thorade** [BorisChumichev/modelicaSublimeTextPackage#2]
Thanks for sharing this Package, I just installed Sublime and your Package, maybe I will completely switch from Notepad++.
I found one small problem: If there is a semicolon in the `annotation(Documentation(info` then the highlighting as comment is turned off for the following lines.

**Comment by BorisChumichev** [comment]
Thanks for creating an issue on that! Package is not well tested yet so feedback from first users is really appreciated. I'll try to fix this in a day or two. Please tell if you will find any other bugs.

**Comment by BorisChumichev** [comment]
fixed that
