### ISSUE TITLE
lightshow

### ISSUE THREAD

**Issue by thorade** [BorisChumichev/modelicaSublimeTextPackage#3]
Just an idea: 
As your package is also used for the github syntax highlight, 
you could mention that somewhere and possibly add a link to 
https://github.com/github/linguist 
and especially to Lightshow:
https://github-lightshow.herokuapp.com/

https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2FBorisChumichev%2FmodelicaSublimeTextPackage%2Fblob%2Fmaster%2FModelica.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fmodelica%2FModelica%2Fblob%2Frelease%2FModelica%25203.2.1%2FElectrical%2FAnalog%2FLines.mo&code=

https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting

**Comment by thorade** [comment]
And in your `README.md` you could add a link to 
http://borischumichev.github.io/modelicaSublimeTextPackage/

**Comment by BorisChumichev** [comment]
I didn't even knew linguist utilizes TextMate-compatible syntax definitions. Thanks for pointing this out!

**Comment by thorade** [comment]
Thanks for the changes! Closing this issue.

github used to use pygments, but at some point they switched to the current system. 
Maybe because they also use TextMate-compatible grammar for [Atom](https://atom.io/)?

For a discussion on Modelica syntax highlight for github/linguist see this issue:
https://github.com/github/linguist/issues/2053
